spring:
    datasource:
        url: jdbc:mariadb://localhost/root
        driverClassName: org.mariadb.jdbc.Driver
        username: root
        password: root
    jpa:
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        hibernate:
            ddl-auto: create
        # show-sql: true
        # properties:
        #    hibernate:
        #        format_sql: true

auth:
  jwtExpirationMs: 600000
  jwtSecret: JWTSuperSecretKey